### ISSUE TITLE
can't run db in mainflux

### ISSUE THREAD

**Issue by digoptical22** [mainflux/mainflux#1524]
Setting Docker and docker compose (20.10 and  1.29) 
When i run docker-compose -f docker/addons/influxdb-writer/docker-compose.yml up -d
the error is 
![image](https://user-images.githubusercontent.com/58322053/145430838-0beed846-04c3-47ed-ad4d-9ee4d974748e.png)

**Comment by mteodor** [comment]
you need to specify env file location 
`docker-compose --env-file docker/.env -f docker/docker-compose.yml up`

**Comment by digoptical22** [comment]
thank you mteodor!!!!!!!!!

**Comment by digoptical22** [comment]
![image](https://user-images.githubusercontent.com/58322053/145435199-f9f38e0e-3538-43e3-a810-099f8bb4b9c7.png)
I think this command is correct, right? @mteodor
